# Dockerfile to demonstrate the behaviour of ENTRYPOINT
# Build from base image busybox:latest
FROM busybox:latest
#  Author: Victor
LABEL maintainer="Victor Moringa School <victor.njonge@moringaschool.com>"
# Set entrypoint command
ENTRYPOINT ["echo", "Dockerfile ENTRYPOINT demo from Moringa DevOps course"]

RUN This will not work
